### ISSUE TITLE
DictionaryInventoryRepository... Singleton Pattern

### ISSUE THREAD

**Issue by drewburlingame** [RHeimbeck/SimpleInventory#1]
I have a couple of questions about the use of the Singleton pattern.  
1. What factors do you consider when deciding when to use (and not use) this pattern.
2. You used the double locking strategy.  What is another way of initializing the Singleton?

**Comment by RHeimbeck** [comment]
Hi Drew,
1. Factors determining using a singleton: Is the system multi-threaded and
   accessing a common resource that otherwise has no built-in exclusion
   mechanisms.  For instance, in the code example we have a local common data
   repository that can be accessed by simultaneous users (each on a separate
   thread) and also by the 'expiring' service on its own thread.  All
   accessors need to see the same data rather than their own instance of the
   data, so right there the system necessitates some sort of singleton
   resource.  Now if the accessors were utilizing a database instead of a
   local data store, we would not need a singleton since the database itself
   would provide that for use.  We would though still need to lock the tables
   during write and delete operations so as to keep data integrity across
   multiple simultaneous accesses.
2. I used a double locking strategy that is thread safe but it is a
   "lazy-load" pattern in that it gets initialized during the first access.
   Another way of initializing the singleton object would be to create a
   sealed class with a static instance of the "Instance" property that will be
   initialized just once by the system during startup.  Yet another way is to
   use the .Net 4's Lazy<T> type.  There are five versions of Singleton
   pattern described in this article "
   http://csharpindepth.com/Articles/General/Singleton.aspx".  I choose a
   thread-safe yet simple to understand pattern.  Admittedly, I did have to
   read this and another article to remember the details for implementing a
   Singleton once I realized I needed one for this sample project. :)
